[Graphics]
fullScreen = false
windowWidth = 1280
windowHeight = 720
windowTitle = 

[Text]
textSpeed = 1.0
textSize = 32
;fontPath = resource/font/Noto_Sans_SC/static/NotoSansSC-SemiBold.ttf
fontPath = D:\Downloads\GSdefaultfonts.ttf

[I18n]
mainLanguage = 0
secondaryLanguage = 2
uiLanguage = 0

[Save]
maxSaveCount = 80
savePathFormat = save/{:03d}.sav

[Audio]
volumes = 0.8